### ISSUE TITLE
Error running xshem from xschem_sky130 directory

### ISSUE THREAD

**Issue by abhisupa** [StefanSchippers/xschem_sky130#1]
Hi Stefan,

I am seeing following error while running xschem from xschem_sky130 direction
my directory has following files
![image](https://user-images.githubusercontent.com/68303504/110284199-44248c80-7f96-11eb-8fcd-097d327dd1e6.png)

Output error is 
![image](https://user-images.githubusercontent.com/68303504/110284102-1dfeec80-7f96-11eb-8dea-7a934fa28f2f.png)

Thanks and regards,
Abhishek

**Comment by StefanSchippers** [comment]
Hi, you installed xschem by doing sudo apt install, but this installs a **very** old ubuntu pre built package. 
You need to install xschem from sources, by doing ./configure, make, sudo make install.

**Comment by abhisupa** [comment]
Hi Stefan, 
I am running into following issue.
![image](https://user-images.githubusercontent.com/68303504/110344674-95f30400-7fe2-11eb-8fe3-d0b73a2aaee0.png)

**Comment by StefanSchippers** [comment]
just do ./bin/xschem
