### ISSUE TITLE
.xschemrc is not present after installing skywater

### ISSUE THREAD

**Issue by Magaspa** [StefanSchippers/xschem_sky130#13]

**Comment by Magaspa** [comment]
![IMG-20220915-WA0005](https://user-images.githubusercontent.com/56870218/190391034-31c191bc-0236-409f-a8f2-f348f39ed0ad.jpg)

**Comment by StefanSchippers** [comment]
The file is called `xschemrc` and not `.xschemrc`. If you want to work with sky130 you need to install `open_pdks`, which will install all the spice models, digital cell characterization data and xschem libraries. After installing open_pdks you will have the xschemrc file located in <your install root>/share/pdk/sky130A/libs.tech/xschem/xschemrc. Create a new empty directory, go into this directory, copy the above xschemrc file into it and start xschem from that directory.

**Comment by StefanSchippers** [comment]
If you want you can install xschem_sky130 alone, but then you must supply the spice models yourself. Open_pdks gets all the needed stuff from skywater-pdk, does numerous corrections , gets the xschem_sky130 repository and installs everything .
If you install xschem_sky130 alone  the xschemrc file should be there. Look [here](https://github.com/StefanSchippers/xschem_sky130).

**Comment by StefanSchippers** [comment]
If you installed xschem_sky130 using a docker / some sandbox environment and xschemrc is missing please contact the container creators.
