### ISSUE TITLE
is there an example of a circuit, ready for layout?

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem_sky130#16]
in the top.sch are links to a few examples. but i think the only one that had some ESD-protection was the buck-converter, and that didnt had any bonding-pads and also no ESD-protection-diodes, only MOSFETs. 

is there some example available using some analog and some digital IOs with all the necessary protection and bonding pads?

**Comment by StefanSchippers** [comment]
May be this [video](https://www.youtube.com/watch?v=jBrBqhVNgDo) can be a starting point. Most of the submissions are done with efabless caravel infrastructure.
https://github.com/efabless/caravel
