### ISSUE TITLE
Installation of magic and skywater pdk

### ISSUE THREAD

**Issue by Prabha1010** [StefanSchippers/xschem_sky130#17]
I was watching your video to install magic and skywater pdk, but the links were not the same in open_pdks 
I installed magic and then skywater pdk as described withe ./configure and make 
Got this error with make install. Can you please help with this 
cp: cannot create regular file '/usr/local/bin/magic': Permission denied
make[2]: *** [Makefile:87: /usr/local/bin/magic.sh] Error 1
make[2]: Leaving directory '/home/prabha/projects/foundry/skywater-pdk/magic/tcltk'
make[1]: *** [Makefile:94: install-tcl-real] Error 2
make[1]: Leaving directory '/home/prabha/projects/foundry/skywater-pdk/magic'
make: *** [Makefile:91: install-tcl] Error 2
prabha@DESKTOP-E32V3A5:~/projects/foundry/skywater-pdk/magic$

**Comment by StefanSchippers** [comment]
By default programs are installed in /usr/local. This is a system directory. You must be root to do that, so just add `sudo` before `make install`:
```
sudo make install
```
