### ISSUE TITLE
TCL error

### ISSUE THREAD

**Issue by Ggurukmm** [StefanSchippers/xschem_sky130#25]
![IMG_20240925_201818](https://github.com/user-attachments/assets/da8f852d-f8b4-446d-9d4c-1ebec62aaa13)

Hi sir 
I got this problem while through this directory that is xschem/xschem_library/xschem_sky130

**Comment by StefanSchippers** [comment]
The shell variable HOME must be present on a unix system
Before running xschem set this variable in the terminal:
`export HOME /home/guru`

**Comment by StefanSchippers** [comment]
It seems that in your xschemrc you are using `$HOME`. This is incorrect, the `HOME` we need is a shell variable, not a TCL global variable, so the correct reference for `HOME` in the `xschemrc` file is : `$env(HOME)`
