### ISSUE TITLE
Can't find sky130_fd_sc_hd.spice

### ISSUE THREAD

**Issue by zhengshuaige66** [StefanSchippers/xschem_sky130#8]
Hi Stefan, 
    I can't find sky130_fd_sc_hd.spice in my sky-water folder. Does this file exist after installation or do we need to write it ourselves?
![image](https://user-images.githubusercontent.com/52859848/159713337-f80d4d98-cf9d-4546-a33e-6381cdfc1687.png)
![image](https://user-images.githubusercontent.com/52859848/159713414-2921f71f-4f32-4384-9664-d24d4bbc5186.png)

**Comment by StefanSchippers** [comment]
You need to install open_pdks as explained in this [video](https://www.youtube.com/watch?v=KgBLByOkJxA), then the file you are looking for will be in /<install_path>/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/spice/. It is now assumed you don't use skywater-pdk directly, but install it with open_pdks. Open_pdks takes care of downloading the skywater-pdk, applying some corrections and also downloading xschem_sky130 libraries. See instructions [here](http://opencircuitdesign.com/open_pdks/index.html).

**Comment by zhengshuaige66** [comment]
thank you very much. I have found it!
